name: Deploy to GCS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  # set your bucket here (or reference another secret/env)
  BUCKET_NAME: find_zubair_test/dataproc_work
  CODE_SUBDIR: products/py_modules

jobs:
  push-to-gcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check OIDC token
      run: |
        echo "Token: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
        echo "URL: $ACTIONS_ID_TOKEN_REQUEST_URL"

    - id: auth
      uses: google-github-actions/auth@v2.0.0  
      with:
        workload_identity_provider: 'projects/611054035776/locations/global/workloadIdentityPools/github-pool/providers/github'
        service_account: '611054035776-compute@developer.gserviceaccount.com'

    - name: Set up gcloud & gsutil
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        # optional: install components
        install_components: gsutil

    - name: Download latest pydeequ wheel from PyPI
      run: |
        python3 -m pip install --upgrade pip
        mkdir -p wheels
        # --no-deps so we only pull the wheel itself
        pip download pydeequ --only-binary=:all: --no-deps -d wheels
        echo "Found wheel:"
        ls wheels

    - name: Upload pydeequ wheel to GCS
      run: |
        gsutil cp wheels/*.whl gs://$BUCKET_NAME/$CODE_SUBDIR/

    - name: Copy library modules to GCS
      run: |
        # create the target folder if you want (gsutil will auto-create)
        gsutil -m cp \
          src/deequ_checks.py \
          src/etl.py \
          src/spark_builder.py \
          src/writer.py \
          gs://$BUCKET_NAME/$CODE_SUBDIR/

    - name: Copy main.py to GCS root
      run: |
        gsutil cp src/main.py gs://$BUCKET_NAME/products/main.py